#localhost:8085/swagger-ui/index.html
#localhost:8085/h2

server:
  port: '8085'
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: 'jdbc:h2:mem:mmsdb'
    name: mmsdb
    driverClassName: org.h2.Driver
    username: sa
    schema: 'classpath:db/schema.sql'
    data: 'classpath:db/data.sql'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    jcache:
      config: 'classpath:ehcache.xml'
'#spring':
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
